services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    # controllers
    jalismrs_globals.controller.globals_controller:
        arguments:
            $controllerService: '@jalismrs_globals.controller_service.globals_controller_service'
        calls:
            - setContainer:
                $container: '@Psr\Container\ContainerInterface'
        class: 'Jalismrs\Symfony\Bundle\JalismrsGlobalsBundle\Controller\GlobalsController'
        tags:
            - 'controller.service_arguments'
    
    # controller-services
    jalismrs_globals.controller_service.globals_controller_service:
        arguments:
            $parameters: '%jalismrs_globals.parameters%'
        class: 'Jalismrs\Symfony\Bundle\JalismrsGlobalsBundle\ControllerService\GlobalsControllerService'
