services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_globals.globals_service:
        class: 'Jalismrs\Symfony\Bundle\JalismrsGlobalsBundle\GlobalsService'
        arguments:
            $parameters: '%jalismrs_globals.parameters%'
    
    #Jalismrs\Symfony\Bundle\JalismrsGlobalsBundle\GlobalsService: '@jalismrs_globals.globals_service'

    jalismrs_globals.globals_container:
        class: 'Jalismrs\Symfony\Bundle\JalismrsGlobalsBundle\Controller\GlobalsController'
        tags:
            - 'controller.service_arguments'
