services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_globals.globals_service:
        class: 'Jalismrs\Symfony\Bundle\JalismrsGlobalsBundle\GlobalsService'
    
    Jalismrs\Symfony\Bundle\JalismrsGlobalsBundle\GlobalsService: '@jalismrs_globals.globals_service'
